### PR TITLE
feat: add block key method

### PR DESCRIPTION
**Pull request by ThomasKoscheck**
Hi, 
I added the Key.Block method and increased minor version

### CODE REVIEW

**Comment by artemlos** [comment]
@ThomasKoscheck Thanks for the PR! I will review it during next week and get back.

**Comment by ThomasKoscheck** [comment]
Hey, are there any updates on this? Would like to see the method in the official package :smile:

**Comment by artemlos** [comment]
@ThomasKoscheck Hi again! I have now reviewed the PR and will merge it to master. I made two changes:
* Changed versioning to 1.0.12 from 1.1.0
* Renamed the method to BlockKey to make it consistent with other SDKs.

Thanks again for submitting the PR :)

**Comment by artemlos** [comment]
@ThomasKoscheck It's now live on npm.

**Pull request merged**
